InventoryERP_Project/Controllers/CategoriesController.cs
using InventoryERP_Project.Models;
using InventoryERP_Project.Utils;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InventoryERP_Project.Controllers
{
    public class CategoriesController : Controller
    {
        readonly InventoryDbContext db = null;
        public CategoriesController(InventoryDbContext db) { this.db = db; }
        public IActionResult Index(int? typeid)
        {
            ViewBag.TypeId = typeid;
            ViewBag.ProductTypes = db.ProductTypes.ToList();
           
                var data = db.Categories.Where(x=> x.Product_Type_Id==typeid.Value && x.Is_Deleted==0).Where(x => x.Is_Deleted == 0).ToList();
                return View(data);
          
            
        }
        public IActionResult Create()
        {
            ViewBag.ProductTypes = db.ProductTypes.ToList();
            return View();
        }
        [HttpPost]
        public IActionResult Create(Category category)
        {
            if (ModelState.IsValid)
            {
                category._Key = Util.RandomString(32);
                category.Is_Deleted = 0;
                db.Categories.Add(category);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }
        public IActionResult CreateMultiple(int? typeid)
        {
            ViewBag.TypeId = typeid;
            ViewBag.ProductTypes = db.ProductTypes.ToList();
            ViewBag.Categories = typeid.HasValue ? db.Categories.Where(x => x.Product_Type_Id == typeid).ToList() : null;
            return View();
        }
        [HttpPost]
        public ActionResult SaveAll(List<Category> categories)
        {
            if (ModelState.IsValid)
            {
                foreach(var c in categories)
                {
                    c._Key = Util.RandomString(32);
                    c.Is_Deleted = 0;
                    db.Categories.Add(c);
                }
                db.SaveChanges();
                var data  =db.Categories.Where(x => x.Product_Type_Id == categories[0].Product_Type_Id).ToList();
                return Json(data);
            }
            return new EmptyResult();
        }
        public PartialViewResult ProductList(int typeid)
        {
            return PartialView("_ProductList_By_Type");
        }
    }
}

InventoryERP_Project/Controllers/ProductTypesController.cs
using InventoryERP_Project.Models;
using InventoryERP_Project.Utils;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InventoryERP_Project.Controllers
{
    public class ProductTypesController : Controller
    {
        readonly InventoryDbContext db=null;
        public ProductTypesController(InventoryDbContext db) { this.db = db; }
        public IActionResult Index(string search="")
        {
            ViewBag.Search = search;
            if (!string.IsNullOrEmpty(search))
            {
                var data = this.db.ProductTypes
                    .Where(x => x.Name.ToLower().StartsWith(search.ToLower()))
                    .Where(p => p.Is_Deleted == 0)
                    .ToList();
                return View(data);
            }
            else
                return View(this.db.ProductTypes.Where(p=> p.Is_Deleted == 0).ToList());
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(ProductType productType)
        {
            if (ModelState.IsValid)
            {
                productType._Key = Util.RandomString(32);
                productType.Is_Deleted = 0;
                db.ProductTypes.Add(productType);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(productType);
        }
        public IActionResult DeleteSelected(int[] ids)
        {
            foreach(int i in ids)
            {
                var existing = db.ProductTypes.FirstOrDefault(x => x.Id == i);
                if (existing != null)
                    existing.Is_Deleted = 1;
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult Delete (int Id)
        {
            var existing = db.ProductTypes.FirstOrDefault(x => x.Id == Id);
            if (existing != null)
                existing.Is_Deleted = 1;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult Edit(int id, string _Key)
        {
            var data = db.ProductTypes.FirstOrDefault(x => x.Id == id);
            if (data == null)
                return NotFound();
            else
            {
                if (data._Key != _Key)
                    return BadRequest();
            }
            
            return View(data);
        }
        [HttpPost]
        public IActionResult Edit(ProductType productType)
        {
            if (ModelState.IsValid)
            {
                var data = db.ProductTypes.FirstOrDefault(x => x.Id == productType.Id);
                if (data == null)
                    return NotFound();
                else
                {
                    if (data.Id != productType.Id)
                        return BadRequest();
                    else
                         if (data._Key != productType._Key)
                        return BadRequest();

                }
                db.Entry(productType).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(productType);
        }
    }
}

InventoryERP_Project/Views/Categories/Create.cshtml
@model Category
@{
    ViewData["Title"] = "Create";
}

<div class="border px-2 mb-1">

    <h3>Create Category</h3>
    <form method="post" asp-controller="Categories" asp-action="Create">
        <div class="form-group row mb-1">
            <label asp-for="ProductType" class="col-form-label col-2"></label>
            <div class="col-4">
                <select class="form-select" asp-for="Product_Type_Id" asp-items="@(new SelectList(ViewBag.ProductTypes, "Id","Name"))">
                    <option value=""></option>
                </select>
                
                <span asp-validation-for="Product_Type_Id" />
            </div>
        </div>
        <div class="form-group row mb-1">
            <label asp-for="Name" class="col-form-label col-2"></label>
            <div class="col-4">
                <input type="text" asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" />
            </div>
        </div>
        <div class="form-group row mb-1">
            <label asp-for="Description" class="col-form-label col-2"></label>
            <div class="col-4">
                <textarea type="text" asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" />
            </div>
        </div>
        <div class="form-group row mb-1">

            <div class="col-4 offset-2">
                <button type="submit" class="btn btn-primary">Save</button>
                <button type="reset" class="btn btn-secondary">Reset</button>
            </div>
        </div>
    </form>
</div>

@section Styles
{
    <link href="~/libs/boostrap-icon/font/bootstrap-icons.css" rel="stylesheet" />

}
@section Scripts
{

    <script src="~/libs/jquery/jquery.min.js"></script>
    <script src="~/libs/validation/jquery.validate.min.js"></script>

    <script src="~/libs/validation/jquery.validate.unobtrusive.min.js"></script>
}

InventoryERP_Project/Views/Categories/CreateMultiple.cshtml
@model Category
@{
    ViewData["Title"] = "CreateMultiple";
}

<h1>Create Multiple Category</h1>
<div>
    <form method="post" asp-controller="Categories" asp-action="CreateMultiple" id="formType">
        
        <div class="form-group row">
            <div class="form-group row mb-1">
                <label asp-for="ProductType" class="col-form-label col-2"></label>
                <div class="col-4">
                    <select class="form-select" id="typeid" name="typeid" asp-items="@(new SelectList(ViewBag.ProductTypes, "Id","Name", ViewBag.TypeId))">
                        <option value="">None</option>
                    </select>

                    <span asp-validation-for="Product_Type_Id" />
                </div>
            </div>
        </div>
    </form>
        <div class="row">
            <div class="col-8">
                <h3>Existing Categories</h3>
                <form id="categoryForm" method="post" asp-controller="Categories" asp-action="SaveMultiple">
                   
                   
                    <table class="table table-bordered">
                        <thead class="bg-light">
                            <tr>
                                <th>Category</th>
                                <th>Description</th>
                                <th class="text-end me-1" style="width:90px"><button type="button" id="add" class="btn btn-secondary btn-sm"><i class="bi bi-plus"></i></button></th>
                            </tr>
                        </thead>
                        <tbody id="tbl">
                            @if (ViewBag.Categories != null)
                            {


                                @foreach (Category x in ViewBag.Categories as IEnumerable<Category>)
                                {
                                    <tr>
                                        <td>@x.Name</td>
                                        <td colspan="2">@x.Description</td>
                                    </tr>
                                }

                            }
                        </tbody>
                    </table>
                    
                </form>
                
            </div>
            <div class="col-12">
                <table class="table table-bordered" id="newData">
                    <thead class="bg-light">
                        <tr>
                            <th>Category</th>
                            <th>Description</th>
                            <th class="text-end me-1" style="width:90px">Action</th>
                        </tr>
                    </thead>
                    <tbody>

                    </tbody>
                </table>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="d-grid mx-4">
                        <button class="btn btn-primary" type="button" id="saveAll">Save</button>
                        
                    </div>
                </div>
            </div>

        </div>
   
</div>
<div class="modal" tabindex="-1" id="addModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Modal title</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-12">
                        <form id="addForm" name="addForm">
                            <div class="form-group row mb-1">
                                <label asp-for="Name" class="col-form-label col-2"></label>
                                <div class="col-4">
                                    <input asp-for="Name" class="form-control col-6" style="width:250px" />
                                    <span asp-validation-for="Name" class="d-flex text-danger" style="width:250px"></span>
                                </div>
                            </div>
                            <div class="form-group row mb-1">
                                <label asp-for="Description" class="col-form-label col-2"></label>
                                <div class="col-4">
                                    <textarea asp-for="Description" class="form-control col-6"style="width:250px" ></textarea>
                                    <span asp-validation-for="Description" class="d-flex text-danger" style="width:250px"></span>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" form="addForm" id="addToTable">Save changes</button>
            </div>
        </div>
    </div>
</div>
@section Styles
{
    <link href="~/libs/boostrap-icon/font/bootstrap-icons.css" rel="stylesheet" />

}
@section Scripts
{

    <script src="~/libs/jquery/jquery.min.js"></script>
    <script src="~/libs/validation/jquery.validate.min.js"></script>

    <script src="~/libs/validation/jquery.validate.unobtrusive.min.js"></script>
    <script>
    var myModal;
    var dataToAdd = [];
    $(() => {
        $("#typeid").change(() => {
            $("#formType").submit();
        });
        myModal = new bootstrap.Modal(document.getElementById('addModal'), {
            backdrop: true
        });
        $("#add").click(() => {
            myModal.show();
        });
        $("#addToTable").click(() => {
            if ($("#addForm").valid()) {
                console.log('OK');
                dataToAdd.push({ Name: $("#Name").val(), Description: $("#Description").val(), Product_Type_Id: $("#typeid").val() });
                //console.log(dataToAdd);
                myModal.hide();
                $("#addForm").trigger('reset');
                showNewData();
            }
        });
        $(document).on("click", "button.del", function () {
            var i= $(this).data("index");
            dataToAdd.splice(i, 1);
            showNewData();
        });
        $("#saveAll").click(() => {
            //console.log(dataToAdd);
            $.ajax({
                method: 'POST',
                dataType: 'json',
                //converters: { "text html": true},
                url: "/Categories/SaveAll",
                data: {
                    categories: dataToAdd
                },
                success: result => {
                    $("#tbl").empty();
                    for (var i = 0; i < result.length; i++) {
                        $("#tbl").append(
                            `<tr>
                                <td>${result[i].name}</td>
                                <td colspan="2">${result[i].description}</td>
                             </tr>`
                        );
                    }
                    $("#newData tbody").empty();
                }
            });
        })
    });
    function showNewData() {
        $("#newData tbody").empty();
        dataToAdd.forEach((x, i) => {
            $("#newData tbody").append(
                `<tr>
                    <td>${x.Name}</td>
                    <td>${x.Description}</td>
                    <td><button class='btn btn-danger btn-sm del' data-index=${i}><i class='bi bi-trash'></i></button></td>
                  </tr>`
            );
        })

    }
    </script>
}

InventoryERP_Project/Views/Categories/Index.cshtml
@model IEnumerable<Category>
@{
    ViewData["Title"] = "Index";
    var i = 0;
}

<div class="row">
    <div class="col-12">
        <h3>Product Type Information</h3>
        <div class="d-flex justify-content-end mb-1">
            <form asp-controller="Categories" asp-action="DeleteSelected" id="delForm">

                <button type="button" id="delSelected" class="btn btn-secondary mr-1">Delete selected items</button>
            </form>


        </div>
        <div class="d-flex justify-content-end mb-1">
            <div class="me-auto" style="width: 250px">
                <form asp-controller="Categories" asp-action="Index" class="mr-1" id="typeSelect">
                    <div class="input-group ">
                        <select name="typeid" id="typeid" class="form-select" asp-items="@(new SelectList(ViewBag.ProductTypes, "Id","Name", ViewBag.TypeId))">
                            <option value=""></option>
                        </select>
                    </div>

                </form>

            </div>
            <form asp-controller="Categories" asp-action="Index" class="mr-1">
                <div class="input-group ">
                    <input type="text" class="form-control" value="@ViewBag.Search" name="search" aria-describedby="button-addon2">
                    <button class="btn btn-outline-secondary" type="submit" id="button-addon2"><i class="bi bi-search"></i></button>
                </div>

            </form>
            <a asp-controller="Categories" asp-action="Create" class="btn btn-primary ms-2"><i class="bi bi-plus"></i> Add New</a>
            <a asp-controller="Categories" asp-action="CreateMultiple" title="Add multple" class="btn btn-primary  ms-1"><i class="bi bi-plus-circle-dotted"></i> Add Multiple</a>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-12">
        @if (Model != null)
        {
            <table class="table table-bordered">
                <thead class="bg-light">
                    <tr>
                        <th>#</th>
                        <th>Product Type</th>
                        <th>Category</th>
                        <th>Description</th>
                        <th>Action</th>
                        <th>
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" value="" id="checkAll">
                                <label class="form-check-label" for="flexCheckChecked">

                                </label>
                            </div>
                        </th>

                    </tr>
                </thead>
                <tbody>
                    @foreach (var x in Model)
                    {
                        <tr>
                            <td>
                                @(++i)
                            </td>
                            <td>@x.ProductType.Name</td>
                            <td>@x.Name</td>
                            <td>@x.Description</td>
                            <td>
                                <div class="d-flex">
                                    <a class="btn btn-secondary btn-sm mr-1" asp-controller="ProductTypes" asp-action="Edit" asp-route-id="@x.Id" asp-route-_Key="@x._Key"><i class="bi bi-pencil"></i></a>
                                    <form class="ms-2" asp-controller="ProductTypes" asp-action="Delete" id="delSingleForm">
                                        <input type="hidden" name="Id" value="@x.Id" />
                                        <button type="submit" class="btn btn-secondary btn-sm mr-1"><i class="bi bi-trash"></i></button>
                                    </form>
                                </div>
                            </td>
                            <td>
                                <div class="form-check">
                                    <input class="form-check-input chk" type="checkbox" data-pk="@x.Id">
                                    <label class="form-check-label" for="flexCheckChecked">

                                    </label>
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
    </div>
</div>
@section Styles
{
    <link href="~/libs/boostrap-icon/font/bootstrap-icons.css" rel="stylesheet" />

}
@section Scripts
{

    <script src="~/libs/jquery/jquery.min.js"></script>
    <script>
        $(() => {
            $("#typeid").change(() => {
                $("#typeSelect").submit();
            })
        $("#checkAll").click(function () {
            //console.log($(this));
            $('input:checkbox').prop('checked', this.checked);
        });
        $("#delSelected").click(() => {
            if ($(".chk:checked").length == 0) return;

            $(".chk").each((id, el) => {
                if ($(el).is(":checked")) {
                    var id = $(el).data('pk');
                    $("#delForm").append(`<input type='hidden' name='ids' value=${id} />`);
                }

            });
            $("#delForm").submit();
        });
    });
    </script>
}

InventoryERP_Project/Views/Categories/_CategoryFormRow.cshtml
@model Category
@{ 
    
    var name = $"Category[{ViewBag.Index}].Name";
    var id = $"Category_{ViewBag.Index}_Name";
    var desc = $"Category[{ViewBag.Index}].Description";
    var iddesc = $"Category_{ViewBag.Index}_Description";
    var nametype = $"Category[{ViewBag.Index}].Product_Type_Id";
}
<tr data-index="@ViewBag.Index">
    <td>
        <input type="hidden" name="@nametype" value="@ViewBag.TypeId" />
        <input asp-for="Name" name="@name" id="@id"  class="form-control" />
        <span asp-validation-for="@name" data-valmsg-for="@name"></span>
    </td>
    <td>
        <input asp-for="Description" name="@desc" id="@iddesc" class="form-control" />
        <span asp-validation-for="@desc" data-valmsg-for="@desc"></span>
    </td>
</tr>

InventoryERP_Project/Views/Categories/_ProductList_By_Type.cshtml
@model IEnumerable<Category>


@foreach (Category x in Model)
{
    <tr>
        <td>@x.Name</td>
        <td colspan="2">@x.Description</td>
    </tr>
}